##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: ms-auth
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: /h2
  profiles:
    include:

adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "db_auth"
    schema: "public"
    username: "gestor"
    password: "123456"