-- Table: public.roles
-- DROP TABLE IF EXISTS public.roles;
CREATE TABLE IF NOT EXISTS public.roles
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT roles_name_key UNIQUE (name)
)
TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.roles
    OWNER to gestor;

-- Table: public.users
-- DROP TABLE IF EXISTS public.users;
CREATE TABLE IF NOT EXISTS public.users
(
    user_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    document_number character varying(50) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    birth_date timestamp without time zone,
    address character varying(255) COLLATE pg_catalog."default",
    phone character varying(50) COLLATE pg_catalog."default",
    email character varying(150) COLLATE pg_catalog."default" NOT NULL,
    base_salary numeric(15,2) NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT 'changeme'::character varying,
    role_id bigint NOT NULL DEFAULT 1,
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_document_number_key UNIQUE (document_number),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT fk_role FOREIGN KEY (role_id)
        REFERENCES public.roles (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE RESTRICT
)
TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.users
    OWNER to gestor;

-- ==============================================
-- CREAR ÍNDICES ADICIONALES
-- ==============================================

-- Índice para búsquedas por email
CREATE INDEX IF NOT EXISTS idx_users_email
    ON public.users USING btree
    (email ASC NULLS LAST)
    TABLESPACE pg_default;

-- Índice para búsquedas por documento
CREATE INDEX IF NOT EXISTS idx_users_document_number
    ON public.users USING btree
    (document_number ASC NULLS LAST)
    TABLESPACE pg_default;

-- Índice para búsquedas por rol
CREATE INDEX IF NOT EXISTS idx_users_role_id
    ON public.users USING btree
    (role_id ASC NULLS LAST)
    TABLESPACE pg_default;

-- ==============================================
-- POBLAR LA TABLA ROLES
-- ==============================================

-- Insertar roles
INSERT INTO public.roles (id, name) VALUES
(1, 'ADMIN'),
(2, 'ADVISOR'),
(3, 'CLIENT')
ON CONFLICT DO NOTHING;

-- Insertar el usuario (sin especificar user_id para que sea autogenerado)
INSERT INTO public.users (
    document_number,
    first_name,
    last_name,
    birth_date,
    address,
    phone,
    email,
    base_salary,
    password_hash,
    role_id
) VALUES (
    '1007599195',
    'Oscar',
    'Sanabria',
    '1990-05-14 19:00:00',
    'Calle 30',
    '3006502125',
    'daniloos2000@gmail.com',
    70000000.00,
    '$2a$12$yuH1RcWQXDfrZFBCvi8XFO2fgjmy0Z4qiZg8sKgIkulRV0LAWoPSW',
    1
);


-- Reiniciar la secuencia de roles para que el próximo ID sea 4
SELECT setval(pg_get_serial_sequence('public.roles', 'id'), 3, true);